---
spring:
    profiles: verb
words: ran,knew,had,saw,bought

---
spring:
    profiles: subject
words: I,You,He,She,It

---
spring:
    profiles: adjetive
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
    profiles: article
words: a,the

---
spring:
    profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
